### PR TITLE
LODs, 3 VFX, Lighting and post-processing

### PR DESCRIPTION
**Pull request by VladNeykov**
### Description
Implemented:
- LODs for Wooden Chairs, Torches, Trees, and Rocks 
- VFX for breaking pottery and wooden crates, and VFX for spawning of players
- Baked lightmaps and added post processing to the **TownMarket_Test_ScenarioWeek** level
- Increased max lights per object on the URP asset to 8 _(please feel free to revert if it's not desirable)_

For more info, please view [this](https://docs.google.com/document/d/1QTlSEPPELWY_lUB5mUGQG59s8-gtj1DXz65q2kGlvks/edit) doc.

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.multiplayer.samples.bitesize?pullRequest=204) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.multiplayer.samples.bitesize?pullRequest=204) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.unity.multiplayer.samples.bitesize?pullRequest=204) it.</sub>

**Review by fernando-cortez — APPROVED** [review]
Pre-approving, but I got a lot of generated warnings about missing LOD meshes on certain prefabs. 

I also notice the FX prefabs were added at the end of the scene hierarchy for testing. We could remove those and I think I spotted a few floating rocks.

Let's have @Elfi0Kuhndorf also take a look at this PR when she's back.

Warnings:
Sub Graph at Assets/Shaders/SubGraphs/ToonLightingModel.shadersubgraph has 5 warning(s), the first is: There is a newer version of this node available. Inspect node for details.

Sub Graph at Assets/Shaders/SubGraphs/AdditionalLights.shadersubgraph has 2 warning(s), the first is: There is a newer version of this node available. Inspect node for details.

Sub Graph at Assets/Shaders/SubGraphs/AdditionalLightsToon.shadersubgraph has 1 warning(s), the first is: There is a newer version of this node available. Inspect node for details.

Sub Graph at Assets/Shaders/SubGraphs/WindAddon.shadersubgraph has 1 warning(s), the first is: There is a newer version of this node available. Inspect node for details.

Warning in Graph at Assets/Shaders/Glass.shadergraph on line -1: Ignoring duplicate keyword line 'multi_compile _ LIGHTMAP_ON'

Shader Graph at Assets/Shaders/Toon_Shaking.shadergraph has 1 warning(s), the first is: There is a newer version of this node available. Inspect node for details.

Warning in Graph at Assets/Shaders/Water_Rivers.shadergraph on line -1: Ignoring duplicate keyword line 'multi_compile _ LIGHTMAP_ON'

Warning in Graph at Assets/Shaders/Water_Sea.shadergraph on line -1: Ignoring duplicate keyword line 'multi_compile _ LIGHTMAP_ON'

File 'BigRock_LOD2' has inconsistent LOD naming (_LOD2 found but no _LOD1).

File 'Tree2_LOD1' has inconsistent LOD naming (_LOD1 found but no _LOD0).

File 'Statue_Mesh_LOD3' has inconsistent LOD naming (_LOD3 found but no _LOD2).

File 'Statue_Mesh_LOD2' has inconsistent LOD naming (_LOD2 found but no _LOD1).

File 'BigRock4_low_LOD1' has inconsistent LOD naming (_LOD1 found but no _LOD0).

File 'Tree2_LOD2' has inconsistent LOD naming (_LOD2 found but no _LOD1).

File 'Tree_LOD2' has inconsistent LOD naming (_LOD2 found but no _LOD1).

File 'BigRock4_low_LOD2' has inconsistent LOD naming (_LOD2 found but no _LOD1).

File 'BigRock2_LOD1' has inconsistent LOD naming (_LOD1 found but no _LOD0).

File 'WoodenChair_LOD1' has inconsistent LOD naming (_LOD1 found but no _LOD0).

File 'Torch_low_LOD2' has inconsistent LOD naming (_LOD2 found but no _LOD1).

File 'Tree_LOD1' has inconsistent LOD naming (_LOD1 found but no _LOD0).

File 'BigRock3_low_LOD1' has inconsistent LOD naming (_LOD1 found but no _LOD0).

File 'Tree3_LOD1' has inconsistent LOD naming (_LOD1 found but no _LOD0).

File 'BigRock3_low_LOD2' has inconsistent LOD naming (_LOD2 found but no _LOD1).

A polygon of Mesh 'RumRumRamsey' in Assets/Art/Props/Statue/Statue_Mesh.fbx is self-intersecting and has been discarded.

File 'Torch_low_LOD1' has inconsistent LOD naming (_LOD1 found but no _LOD0).

File 'BigRock2_LOD2' has inconsistent LOD naming (_LOD2 found but no _LOD1).

File 'BigRock_LOD1' has inconsistent LOD naming (_LOD1 found but no _LOD0).

File 'Tree3_LOD2' has inconsistent LOD naming (_LOD2 found but no _LOD1).

File 'Statue_Mesh_LOD1' has inconsistent LOD naming (_LOD1 found but no _LOD0).

File 'BigRock_LOD2' has inconsistent LOD naming (_LOD2 found but no _LOD1).

File 'Tree2_LOD1' has inconsistent LOD naming (_LOD1 found but no _LOD0).

File 'Statue_Mesh_LOD3' has inconsistent LOD naming (_LOD3 found but no _LOD2).

File 'Statue_Mesh_LOD2' has inconsistent LOD naming (_LOD2 found but no _LOD1).

File 'BigRock4_low_LOD1' has inconsistent LOD naming (_LOD1 found but no _LOD0).

File 'Tree2_LOD2' has inconsistent LOD naming (_LOD2 found but no _LOD1).

File 'Tree_LOD2' has inconsistent LOD naming (_LOD2 found but no _LOD1).

File 'BigRock4_low_LOD2' has inconsistent LOD naming (_LOD2 found but no _LOD1).

File 'BigRock2_LOD1' has inconsistent LOD naming (_LOD1 found but no _LOD0).

File 'Torch_low_LOD2' has inconsistent LOD naming (_LOD2 found but no _LOD1).

File 'Tree_LOD1' has inconsistent LOD naming (_LOD1 found but no _LOD0).

File 'BigRock3_low_LOD1' has inconsistent LOD naming (_LOD1 found but no _LOD0).

File 'Tree3_LOD1' has inconsistent LOD naming (_LOD1 found but no _LOD0).

File 'BigRock3_low_LOD2' has inconsistent LOD naming (_LOD2 found but no _LOD1).

File 'Torch_low_LOD1' has inconsistent LOD naming (_LOD1 found but no _LOD0).

File 'BigRock2_LOD2' has inconsistent LOD naming (_LOD2 found but no _LOD1).

File 'BigRock_LOD1' has inconsistent LOD naming (_LOD1 found but no _LOD0).

File 'Tree3_LOD2' has inconsistent LOD naming (_LOD2 found but no _LOD1).

File 'Statue_Mesh_LOD1' has inconsistent LOD naming (_LOD1 found but no _LOD0).

**Comment by VladNeykov** [comment]
Hi @fernando-cortez ,
Nice catch, the LOD warnings appear only on the first load so I missed that. The issue is that Unity prefers LODs to be exported as sub-objects of the same FBX, and I just added LOD1 and LOD2, but didn't change the original asset. I'll re-export all the LODs as new FBX with sub-meshes. This means that someone should confirm if the original meshes are still needed and remove them.

> I also notice the FX prefabs were added at the end of the scene hierarchy for testing.
Yup, Elfi asked me to create a temp new scene so I left them there for visibility, but happy to remove them if we want to end up using this scene.

For the floating rock, looks like some of the rock prefabs had offsets, I'll fix this along the LOD fixes.

**Comment by VladNeykov** [comment]
Hi @fernando-cortez , all the LOD warnings should be fixed now (that also fixed the floating rock).
The VFX are also removed from the scene and lighting is re-baked.

I hadn't done any shader work, but I also cleared up the shader warnings you mentioned.
Should be all good, thanks for catching these :)

**Comment by fernando-cortez** [comment]
> Hi @fernando-cortez , all the LOD warnings should be fixed now (that also fixed the floating rock). The VFX are also removed from the scene and lighting is re-baked.
> 
> I hadn't done any shader work, but I also cleared up the shader warnings you mentioned. Should be all good, thanks for catching these :)

Awesome, thanks for handling those shader warnings! Yeah the warnings related to this PR are now not showing up anymore. Good to go for me 😀

**Comment by Elfi0Kuhndorf** [comment]
Looks good to me! It is awesome to see the LODs and VFX working. 
One thing I just noticed is that opening the scene takes over 1 minute. Is that to be expected?

**Review by Elfi0Kuhndorf — APPROVED** [review]
Looks good

**Pull request merged**
