### PR TITLE
Multiplayer Use cases for Unity 6 - usability improvements

### PR DESCRIPTION
**Pull request by RikuTheFuffs**
### Description
- Removed runtime network stats monitor from the only scene that had it
- All inputs in various scenes are handled through the new Unity Input System
- The last page of the "Data/Event Synchronization tutorial" redirects to the "Proximity Checks" tutorial
- Multiplayer Play Mode window is now interactable on the last page of all tutorials

### How to test/validate

1. Clone this branch
2. Open it with unity 6000.0.17f1
3. Go through all tutorials, opening the Multiplayer Play Mode Window on the last page: check that it is always interactable
4. Check that there are no calls to the old input system methods (`Input.<method>`) in code
5. Check that no scene has Runtime Network Stats Monitor

### Issue Number(s)
- https://jira.unity3d.com/browse/MTT-9078
- https://jira.unity3d.com/browse/MTT-8682
- https://jira.unity3d.com/browse/MTT-8385

### Contribution checklist
 - [ ] Tests have been added for the project and/or any internal package
 - [ ] Release notes have been added to the [project changelog](../CHANGELOG.md) file
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] JIRA ticket ID is in the PR title or at least one commit message
 - [x] Include the ticket ID number within the body message of the PR to create a hyperlink

### CODE REVIEW

**Comment by gopher-atz** [comment]
from the PR description and tickets i would assume not to see any RNSM, but i do

also MPPM is interactable, but i think the text in the tutorial at that step doesnt emphasize it.
i would expect MPPM to be the first option (not to create a build), also i would expect MPPM window to open (otherwise how would i know that this is interactable?)

see screenshot
MPUseCases

**Comment by RikuTheFuffs** [comment]
> going over the MultiplayerUseCases Tutorial. i did get a few times this error

@gopher-atz nice catch, forgot to push a file, now it should be fixed.

> from the PR description and tickets i would assume not to see any RNSM, but i do

fixed

> i would expect MPPM to be the first option, not to create a build.

Done

> also i would expect MPPM window to be opened

The reason why it is not opened automatically is because we do not "force" users towards a specific workflow when multiple are available. 

> or at least a link/action to open it

The "virtual players" link highlighted in your screenshot leads to the documentation of MPPM, which explains how to open it _and_ set up the virtual player. The information is not bundled in those tutorials as they're focused on explaining other concepts than "how to use MPPM". The latter should be in an in-editor tutorial of the MPPM package (cc @johann-r-unity for awareness / evaluation)

**Comment by gopher-atz** [comment]
the project manifest is still referring to MPPM '1.3.0-pre.2'
we should upgrade that now to the released version '1.3.0' so we can save the auto upgrade and log message for it:

> MPPM has been updated from version '1.3.0-pre.2' to '1.3.0'
> UnityEngine.Debug:ExtractStackTraceNoAlloc (byte*,int,string)
> UnityEngine.StackTraceUtility:ExtractStackTrace () (at C:/UnitySrc/unity/unity/Runtime/Export/Scripting/StackTrace.cs:37)
> UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
> UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
> UnityEngine.Logger:Log (UnityEngine.LogType,object)
> UnityEngine.Debug:Log (object)
> Unity.Multiplayer.Playmode.Workflow.Editor.ProjectDataStore:.ctor (string) (at ./Library/PackageCache/com.unity.multiplayer.playmode@8ee960c94af3/Workflow/Editor/Configuration/ProjectDataStore.cs:60)
> Unity.Multiplayer.Playmode.Workflow.Editor.ProjectDataStore:GetMain () (at ./Library/PackageCache/com.unity.multiplayer.playmode@8ee960c94af3/Workflow/Editor/Configuration/ProjectDataStore.cs:36)
> Unity.Multiplayer.Playmode.Workflow.Editor.WorkflowMainEditorContext:.ctor (Unity.Multiplayer.Playmode.VirtualProjects.Editor.MainEditorContext) (at ./Library/PackageCache/com.unity.multiplayer.playmode@8ee960c94af3/Workflow/Editor/Contexts/WorkflowMainEditorContext.cs:15)
> Unity.Multiplayer.Playmode.Workflow.Editor.VirtualProjectWorkflow:InitializeMPPMContexts () (at ./Library/PackageCache/com.unity.multiplayer.playmode@8ee960c94af3/Workflow/Editor/Workflow/VirtualProjectWorkflow.cs:84)
> Unity.Multiplayer.Playmode.Workflow.Editor.VirtualProjectWorkflow/<>c:<.cctor>b__17_0 () (at ./Library/PackageCache/com.unity.multiplayer.playmode@8ee960c94af3/Workflow/Editor/Workflow/VirtualProjectWorkflow.cs:58)
> Unity.Multiplayer.Playmode.VirtualProjects.Editor.EditorContexts:SendReadyEvent () (at ./Library/PackageCache/com.unity.multiplayer.playmode@8ee960c94af3/VirtualProjects/Editor/Contexts/EditorContexts.cs:56)
> System.Reflection.RuntimeMethodInfo:Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo)
> System.Reflection.MethodBase:Invoke (object,object[])
> UnityEditor.EditorAssemblies:ProcessInitializeOnLoadMethodAttributes () (at C:/UnitySrc/unity/unity/Editor/Mono/EditorAssemblies.cs:142)
> 
>

**Comment by RikuTheFuffs** [comment]
MPPM 1.3.0 requires a minimum version that is higher than the one the project is using. (.22 vs .17).

Since we might want to update all the other packages as well (I.E: NGO to 2.0.0), it'll make sense to wait a few days and then open a new branch to upgrade to the Unity 6 GA version + update all packages to the latest

Also, our changes are not guaranteed to work with trunk. If a PR specifies to use a specific editor version, you should test it with that version only (also because different editor versions might introduce bugs/warnings/problems that the PR author would not be able to reproduce).

When GA is available, we'll need to re-test a lot of other things also because of the update to NGO 2.X. 
We're not doing it in this branch because it would many changes that are unrelated to the scope of the PR.

**Pull request merged**
