### PR TITLE
[MTT-9216] DA Sample Change sort layer and color of fire prefab to bring it to foreground

### PR DESCRIPTION
**Pull request by Elfi0Kuhndorf**
### Description

Change sort layer of fire to bring it to foreground

### Issue Number(s)

https://jira.unity3d.com/browse/MTT-9216
### Contribution checklist
 - [ ] Tests have been added for the project and/or any internal package
 - [ ] Release notes have been added to the [project changelog](../CHANGELOG.md) file
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] JIRA ticket ID is in the PR title or at least one commit message
 - [x] Include the ticket ID number within the body message of the PR to create a hyperlink

### CODE REVIEW

**Comment by gopher-atz** [comment]
looks like this for me:
image
so smoke layer is above fire now, as opposed to the screenshot from the ticket: https://jira.unity3d.com/browse/MTT-9216

**Comment by Elfi0Kuhndorf** [comment]
> looks like this for me: image so smoke layer is above fire now, as opposed to the screenshot from the ticket: https://jira.unity3d.com/browse/MTT-9216

Yes,  I understood the ticket that way that the smoke renders only behind the fire and that that should be fixed. So I changed the sort layer in order to let the smoke render also in front of the fire.

**Review by fernando-cortez — COMMENTED** [review]
So, rendering-wise, it looks great.
But I'm not so sure if this fits the same art style anymore? It's very realistic looking flames + smoke, while the rest of the environment is toon shaded & simplified.
Could we add style to it to make it fit the game look?

**Comment by fernando-cortez** [comment]
Screenshot 2024-11-18 at 11 28 25

Yeah, the simplicity of what it was before helps here, so we might not need the basemap.

**Comment by Elfi0Kuhndorf** [comment]
How about this? 
image

**Pull request closed without merging**
