### PR TITLE
feat: Distributed Authority Sample initial project setup with scene & folder structure [MTT-8913]

### PR DESCRIPTION
**Pull request by fernando-cortez**
### Description
Initial commit for Distributed Authority Sample project.
This includes the initial scene & folder structure setup.
Included as well is a temp script to enable joining into a ServiceLive CMB session.

### Issue Number(s)
[MTT-8913](https://jira.unity3d.com/browse/MTT-8913)

### Contribution checklist
 - [ N/A ] Tests have been added for the project and/or any internal package
 - [ N/A ] Release notes have been added to the [project changelog](../CHANGELOG.md) file
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] JIRA ticket ID is in the PR title or at least one commit message
 - [x] Include the ticket ID number within the body message of the PR to create a hyperlink

### CODE REVIEW

**Comment by Elfi0Kuhndorf** [comment]
When opening the Bootstrap scene I encountered a missing script in the ServicesHelper 
image

**Comment by fernando-cortez** [comment]
> When opening the Bootstrap scene I encountered a missing script in the ServicesHelper image

Ah the script got ignored by Git. Should be there now!

**Review by Elfi0Kuhndorf — APPROVED** [review]
Looks good now (it complains about vivox 'server' is null or empty, but I think that is expected as we did not set up vivox yet)

**Comment by fernando-cortez** [comment]
> Looks good now (it complains about vivox 'server' is null or empty, but I think that is expected as we did not set up vivox yet)

That might actually be a Vivox bug, I believe. Could you pop open the services window, and just open the section for Vivox, and then try again? That fixed it for me.
Vivox is enabled in our Dashboard, so it should initialize as intended.

**Comment by Elfi0Kuhndorf** [comment]
Ah you are right, I tried out the fix you suggested and Vivox did not throw an error anymore!

**Pull request merged**
