### PR TITLE
Feature: Art Pass [MTT-5907]

### PR DESCRIPTION
**Pull request by jilfranco-unity**
### Description
This PR contains a light art pass for the API Diorama! 

Included in this PR:
* Material Updates
* Color tweaks
* UI Visual updates

Future work to be done in a later PR:
* Converting the UI to UIToolkit UI

Here's a video!

https://github.com/Unity-Technologies/com.unity.multiplayer.samples.bitesize/assets/89089503/18ac4ef3-9375-405d-81e5-709a971f1586

### Issue Number(s)
[MTT-5907](https://jira.unity3d.com/browse/MTT-5907)

### Contribution checklist
 - [ ] Tests have been added for the project and/or any internal package
 - [ ] Release notes have been added to the [project changelog](../CHANGELOG.md) file
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] JIRA ticket ID is in the PR title or at least one commit message
 - [x] Include the ticket ID number within the body message of the PR to create a hyperlink

### CODE REVIEW

**Review by RikuTheFuffs — APPROVED** [review]
@jilfranco-unity LGTM, one question: do we also plan to add art for the Welcome Dialog, and the tutorials?
Templates usually have it.

image

**Comment by RikuTheFuffs** [comment]
the welcome dialog looks great. For the tutorials, I'm worried that the mini-screenshot wouldn't work well from the standpoint of readability. What if we used icons to illustrate the concept the tutorial explains?

Some ideas:

1. Network Variables -> a box with data in it (I.E: a number, a string)
2. RPC -> devices that send info to each other (arrows?)
3. Data event -> something along the line of RPC (the tutorial is a mix of 1 and 2)
4. Proximity checks -> a box with an exclamation mark on top of it

**Comment by jilfranco-unity** [comment]
> the welcome dialog looks great. For the tutorials, I'm worried that the mini-screenshot wouldn't work well from the standpoint of readability. What if we used icons to illustrate the concept the tutorial explains?
> 
> Some ideas:
> 
> 1. Network Variables -> a box with data in it (I.E: a number, a string)
> 2. RPC -> devices that send info to each other (arrows?)
> 3. Data event -> something along the line of RPC (the tutorial is a mix of 1 and 2)
> 4. Proximity checks -> a box with an exclamation mark on top of it

Excellent point! I've updated the icons to be more visually descriptive (with updated screenshots and/or reusing icons from our documentation)--please let me know what you think! :)

image
image

**Comment by RikuTheFuffs** [comment]
Way better! Only a note on the 2nd: RPCs _can_ go both ways, so the image might be misinterpreted. Apart from that, which is mainly a nitpick, all good!

**Comment by RikuTheFuffs** [comment]
Remember also to use these import settings for images that are only displayed in the editor (I.E: the welcome dialog)

image

**Comment by jilfranco-unity** [comment]
@RikuTheFuffs I've updated the images per the comments! I think they're much clearer :)

image

The welcome dialog is set to "Editor GUI and Legacy UI"! But should I also use that type for the other images (which are both in the editor and in game)? Or should I use a different type?

**Comment by RikuTheFuffs** [comment]
Thanks! For those that are used in-game, you can't use the "Editor GUI" type, they'll have to stay with Sprite. 
I guess you can merge then :D

**Pull request merged**
