### PR TITLE
[MTT-9279] Fix: Distributed Authority Sample Lighting, Shadow and Shader Fixes

### PR DESCRIPTION
**Pull request by Elfi0Kuhndorf**
### Description

Cal Chiu helped our team and adjusted settings and shader to fix the lighting and shadow display within the project. Further with the help of MingWai we fixed the transparency issue of the water. This PR helps to improve the overall look of the sample.

### Issue Number(s)

https://jira.unity3d.com/browse/MTT-9279

### Contribution checklist
 - [ ] Tests have been added for the project and/or any internal package
 - [ ] Release notes have been added to the [project changelog](../CHANGELOG.md) file
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] JIRA ticket ID is in the PR title or at least one commit message
 - [x] Include the ticket ID number within the body message of the PR to create a hyperlink

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.multiplayer.samples.bitesize?pullRequest=265) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.multiplayer.samples.bitesize?pullRequest=265) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Elfi0Kuhndorf<br/>:x: CalChiu<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.unity.multiplayer.samples.bitesize?pullRequest=265) it.</sub>

**Review by hammerlerobi — APPROVED** [review]
Tested on Mobile and MacOS, works and great improvement.

- Maybe we should remove the uncommented sections from CustomLighting.hlsl? (Can be done later)
- Investigate Shadow Poping in a follow up.

Ready to merge

**Review by fernando-cortez — APPROVED** [review]
Looks absolutely amazing!
Let's add a note in the changelog before merging 😄

**Review by hammerlerobi — APPROVED** [review]
Great improvements

**Pull request merged**
