### PR TITLE
[SpaceShooter] Fix syncing of explosions

### LINKED ISSUE #13: Client not showing FXs
Host shows explosions and other effects.  The client does not show explosion or ship damage effects.

**To Reproduce**
Play game with host and client.  Running 2020.3.9f1 with the latest pull.

**Expected behavior**
Client should have same effects as host:  explosions from shots and damage effects on ship.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Unity Version:  2020.3.9f1
 - MLAPI Version: 0.1.0

### PR DESCRIPTION
**Pull request by das-hund**
Explosions are now spawned over the network just like bullets.

Closes #13

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.multiplayer.samples.bitesize?pullRequest=21) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.multiplayer.samples.bitesize?pullRequest=21) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.unity.multiplayer.samples.bitesize?pullRequest=21) it.</sub>

**Comment by LukeStampfli** [comment]
There is a better/simpler way to do it. (Explosions don't have to be networked we just need to spawn them whenever a bullet despawns). In the next version of MLAPI this will be possible with the `OnNetworkDespawn` callback function.

**Comment by das-hund** [comment]
@LukeStampfli, that makes sense. When will that be released?

**Comment by LukeStampfli** [comment]
We don't have a release date yet which we can share publicly sorry. What we will start soon though is work on our develop branch and update the samples to the latest WIP changes to MLAPI so that once the new version releases we can quickly upgrade the samples.

**Comment by LukeStampfli** [comment]
#24 (Bullet.cs) Has an implementation where we use the new `OnNetworkDespawn` feature to spawn an explosion whenever a bullet gets despawned this allows us to create the explosions directly without needing to have them as NetworkObjects.

We will merge this change into the main branch once the next version of MLAPI gets released.

Closing this as it is no longer relevant. But thanks a lot for the contribution.

**Pull request closed without merging**
