### PR TITLE
Feature: 2D Space Shooter UI Pass using UI Toolkit

### PR DESCRIPTION
**Pull request by jilfranco-unity**
**Description:**

This PR contains an overhaul of the UI for the 2D Space Shooter Bitesize Sample--the old GUI UI has been replaced with new and improved UI Toolkit UI! 

Overall features include:
* New visuals for buttons, input fields, player UI, and power up labels all created and implemented using UI toolkit runtime UI
* More feedback provided to user in Main Menu UI (connection status, field input validity)

Plus the removal of outdated GUI UI!

There's a [known issue for an error that's thrown with UI Toolkit also](https://issuetracker.unity3d.com/issues/error-destroy-may-not-be-called-from-edit-mode-use-destroyimmediate-instead-dot-is-shown-when-exiting-play-mode), so please disregard that

Here's a before an after of the visuals

Before:
https://user-images.githubusercontent.com/89089503/182952232-ea501b07-9f5c-477e-9fe6-4bd92cae6504.mp4

After:
https://user-images.githubusercontent.com/89089503/182951407-4b2d0ec7-9486-4271-ad85-1dfd646a4a23.mp4

### CODE REVIEW

**Comment by chrispope** [comment]
I am getting cartoony/comic sans style feels from the UI buttons in the top left.
However, I don't get the same feels for the player UI and pick UI - are the fonts the same?

Maybe you could try a sci-fi stylised font or present us with a few options?

**Review by LPLafontaineB — COMMENTED** [review]
Should we be able to see the name, hp, and energy of other player characters?
image

**Comment by jilfranco-unity** [comment]
> Should we be able to see the name, hp, and energy of other player characters? image

That is intentional, yes! You can destroy other players so it's useful to be able to see their name and resources

**Comment by jilfranco-unity** [comment]
> Most definitely an improvement.
> 
Thank you! :)

> I am getting cartoony/comic sans style feels from the UI buttons in the top left. However, I don't get the same feels for the player UI and pick-ups UI - are the fonts the same?
> 
The font is the same for the whole game--player, power ups, menu elements

> Definitely clear and readable. Not a matching style in my opinion.
> 
> Maybe you could try a sci-fi stylised font or present us with a few options?

I can try some different fonts! Is that all that seems off or is there other things that I could change (i.e. colors, shape language, overall layout, etc)? Some reference of what you envision would be great too--is there a specific game that you really like the look of that I can reference?

**Review by LPLafontaineB — APPROVED** [review]

**Review by chrispope — APPROVED** [review]

**Review by LPLafontaineB — APPROVED** [review]
Love this! Very nice upgrade

**Comment by fernando-cortez** [comment]
Empty comment to test CLA.

**Pull request merged**
